# Generated by Django 2.1 on 2018-08-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='owner',
            new_name='holder',
        ),
    ]
